# Generated by Django 5.2 on 2025-04-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamboard",
            name="last_view",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
