# Generated by Django 5.2 on 2025-04-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamboard", "0002_streamboard_last_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamboard",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="streamboards/logo/"
            ),
        ),
    ]
